---
- name: Copy test configuration file
  copy: src=files/testfile.conf dest=/home/centos/testfile.conf
- name: Create Web Root
  file:
    path: '{{ docroot }}'
    mode: 775
    state: directory
    owner: centos
    group: centos
  notify:
    - Reload Nginx
- name: List keys simple
  aws_s3:
    bucket: marioarz-apps
    object: /java-app/spring-boot-sample.jar
    dest: /home/centos/spring-boot-sample.jar
    mode: get
