---
# handlers file for /usr/local/etc/ansible/roles/nginx-marioarz
- name: Start Nginx
  service:
    name: nginx
    state: restarted

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
